# Database settings.
database:

  # the name of your JDBC driver
  driverClass: org.hsqldb.jdbcDriver

  # the username
  user: 

  # the password
  password:

  # the JDBC URL
  url: DATABASE_URL

  # any properties specific to JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: io.budgetapp.hibernate.dialect.CustomPostgreSQLDialect
    hibernate.format_sql: true

  validationQuery: SELECT 1

server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: 8080
  registerDefaultExceptionMappers: false

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'io.budgetapp' to DEBUG.
    io.budgetapp: DEBUG

    org.hibernate.SQL: ALL

  appenders:
    - type: console
categories:
  - name: Revenu
    type: INCOME
  - name: Maison
    type: EXPENDITURE
  - name: Transports
    type: EXPENDITURE
  - name: Santé
    type: EXPENDITURE
  - name: Charité/Cadeaux
    type: EXPENDITURE
  - name: Vie quotidienne
    type: EXPENDITURE
  - name: Loisirs
    type: EXPENDITURE
  - name: Epargne
    type: EXPENDITURE
  - name: Dettes
    type: EXPENDITURE
  - name: Divers
    type: EXPENDITURE

budgets:
  Revenu:
    - name: Salaire et primes
    - name: Intérêts
    - name: Dividendes
    - name: Cadeaux reçus
    - name: Remboursement
    - name: Transfert depuis épargne
  Maison:
    - name: Loyer
    - name: Assurances
    - name: Electricité
    - name: Gas
    - name: Eau
    - name: Télephone
    - name: Internet
    - name: Fournitures
    - name: Travaux divers
  Transports:
    - name: Paiement voiture
    - name: Assurance auto
    - name: Essence
    - name: Carte navigo et tickets
    - name: Réparations/Entretien
    - name: Administratif
  Santé:
    - name: Assurance/Mutuelle
    - name: Médecin
    - name: Médicaments
    - name: Vétérinaire
  Charité/Cadeaux:
    - name: Cadeaux donnés
    - name: Dons assos
  Vie quotidienne:
    - name: Courses
    - name: Habillement
    - name: Cours
    - name: Coiffeur
    - name: Animaux
  Loisirs:
    - name: Sorties
    - name: Voyages
  Epargne:
    - name: Epargne
  Dettes:
    - name: Prêt étudiant
    - name: Prêt permis
    - name: Prêt Réjane
  Divers:
    - name: Frais bancaires
    - name: Administratif
